[note]
language = "en"
filename = "data/{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[format.markdown]
link-format = "[[{{filename}}]]"
hashtags = true
colon-tags = false
multiword-tags = false

[lsp]
[lsp.diagnostics]
dead-link = "error"
