name: "Publish"

on:
  push:
    branches:
      - main

  schedule:
    - cron: "22 22 * * *"

  workflow_dispatch:

jobs:
  emanote:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Build the website using emanote 🔧
        run: |
          make build
          mv result/ docs/

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}
